"""Generated protobuf / grpclib stubs.

Generated by `make protoc` from `proto/`. NEVER edit by hand.

The protoc-generated modules use proto-package-absolute imports
(e.g. `import ocpp_gw.v1.gateway_pb2`). To make those resolve when the
files live in `eveys_ocpp._generated.ocpp_gw.v1.*`, we add this
package's directory to sys.path on first import. The grpclib plugin
emits type references inline inside runtime dicts (not just at the
top of the file), so a textual rewrite would need to parse Python —
the sys.path approach handles every form in one line.
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))
